//const parentcontainer = document.querySelector(".parent")

//const childcontainer = document.createElement("div")
//childcontainer.classList.add("child")
//childcontainer.innerText = "i am child"

//parentcontainer.appendChild(childcontainer)
//console.log(childcontainer)

//innerchildcontainer.classList.add("innerchild")
//childcontainer.appendChild(innerchildcontainer)

parentcontainer.innerHTML = 
<div class="child">
    <div class="inner-child"></div>
    </div>