/**
 * @var
 * you can redeclare a variable
 * var name ="francis"
 * var name ="mutunga"
 * /*
 
/*
@let
 * you can redassing  a variable 
 * let name = "francis"
 * let name = "mutunga"
 

 *you can  reassing a variable  
 *let name ="francis"
 /**
  * @cont
  *you cant redeclre a variable




  //DATA TYPES
  /**primitive data types
   * @strings - character/numbers wrapped in quotes- "francis","Dan"."123"
   * @number -Decimal,wholee numbers,negative numbers - 1,1.5, -1
   * @booleans -true or false
   * @undefined -no value assigned 
   * @null -nothing 
   */

  /**
   * Non-primitive data types
   * @list -Arrays -{1,2,3,4,5} ,{"francis","dan"}
   * @objects -Dictionaries (key/value pairs)-{name; ,"francis"}
   */

  //OPERATORS
   /**
    *@ADDITION -+
    *@SUBTRACTION _ -
    @MULTIPLICATION -*
    @DIVISION - /
    @MOULUS - %
    */
   
    const profit = 1000 - 500 - 200
    console.log(profit)
/**
 * @naming rules
 * pascal case ->Thisispascalcaase
 * camelcase ->Thisiscamelcase
 * snake_case->This_is_snake_case
 * kebanb_case->This_is_kebab_case
 */