function add (a, b) { //function declaration (parameters)

//function definition
let num1 =10
let num2 =20
return a + b
}
console.log(add(num1,num2))//function call

//function expression 
const add =function (a,b) {
    return a+b
}
console.log(add(10,20))
//arrow function
const add2 =(a,b)=>{
    return a+b
}
console.log(add2(10,20))

setTimeout(() => {
    console.log("hello world")
    console.log("francis")
}, timeout);

//console.log(add2(10,20))
for (let i = 0; i<=10)
const name ="francis",
const school ="zindua school"
console.log(sentence)

const sentence ="my name is$ {name} currently at ${school}"





const recursive = ()=>{
    if (n <= 2) {
        return n * factorial(n-1)
}
console.log(factorial(6))

const fibonacci =  (n)=>{
    //base case
    if (n === 1 // n ===)
}